### PR TITLE
Updated puppet-redirect url attribute

### PR DESCRIPTION
**Pull request by PatrykSzwer**
Related to https://github.com/Palindrom/palindrom-redirect/issues/1

I have replaced puppet-redirect with palindrom-redirect, but now, when You're redirecting page, everything is working, but You will get error in console:
image

@Mihaiii do You know what caused it and how to fix it?

### CODE REVIEW

**Comment by PatrykSzwer** [comment]
Right now `Go back` button when creating new content stopped working.

**Comment by Mihaiii** [comment]
I can't reproduce.
I navigate to `http://localhost:8080/content/cms`, click on "Create", click "Go back".

**Comment by PatrykSzwer** [comment]
Here's my situation:
repro

**Comment by Mihaiii** [comment]
I see, I can't reproduce it if I run only SignIn + Content, but I can reproduce it with SignIn + Content + Website. I opened an issue for it ( #117 ). I can reproduce it on `develop` branch also so it shouldn't be related with this PR.

**Comment by PatrykSzwer** [comment]
Ok, I'll merge this in that case.

**Pull request merged**
