### PR TITLE
Update elements

### PR DESCRIPTION
**Pull request by Mihaiii**
`paper-tree` doesn't have a hybrid version.
When I had to chose a element for the tree menu, I tried searching for a hybrid element, but could find any. I will look some more into this.

For Starcounter/RebelsLounge#193

### CODE REVIEW

**Comment by Mihaiii** [comment]
For the hybrid version of `paper-tree` I have my own fork because the user that made the hybrid version chose to write bower.json in [this way](https://github.com/andreaskalin/paper-tree/) and I need the dependencies of `paper-tree` to use hybrid versions.

**Comment by warpech** [comment]
> For the hybrid version of `paper-tree` I have my own fork because the user that made the hybrid version chose to write bower.json in [this way](https://github.com/andreaskalin/paper-tree/) and I need the dependencies of `paper-tree` to use hybrid versions.

Maybe add an info about it in https://github.com/vpusher/paper-tree/pull/8?

**Comment by warpech** [comment]
Should I re-review this? I still get a lot of new files in TinyMCE when doing `bower install`

**Comment by Mihaiii** [comment]
After tinymce is installed, we need to use `grunt`.

**Comment by Mihaiii** [comment]
Should I remove tinymce from bower.json?

**Comment by Mihaiii** [comment]
I moved tinymce to another location.
At the end, I deleted `sys` and ran `bower install`.

**Comment by Mihaiii** [comment]
@Joltrix , @habib535 , @bouguila - Someone please review.

**Pull request merged**
