### PR TITLE
Tinymce

### PR DESCRIPTION
**Pull request by Mihaiii**
Replaced ace editor with tinymce.

### CODE REVIEW

**Comment by Mackiovello** [comment]
Something seems to be wrong:

```
GET http://localhost:8080/sys/tinymce/js/tinymce/tinymce.min.js 
content-wrapped-tinymce.html:40 Uncaught TypeError: tinymce.init is not a function
    at HTMLElement.initEditor (http://localhost:8080/Content/elements/content-wrapped-tinymce/content-wrapped-tinymce.html:40:25)
    at HTMLElement.attached (http://localhost:8080/Content/elements/content-wrapped-tinymce/content-wrapped-tinymce.html:66:22)
    at http://localhost:8080/sys/polymer/polymer-micro.html:279:6
    at Object.whenReady (http://localhost:8080/sys/polymer/polymer-micro.html:110:1)
    at HTMLElement.attachedCallback (http://localhost:8080/sys/polymer/polymer-micro.html:270:22)
    at HTMLElement.attachedCallback (http://localhost:8080/sys/polymer/polymer-mini.html:181:22)
    at DomApi.(anonymous function) [as insertBefore] (http://localhost:8080/sys/polymer/polymer-mini.html:1315:26)
    at HTMLTemplateElement._insertChildren (http://localhost:8080/sys/polymer/polymer.html:5370:25)
    at HTMLTemplateElement.render (http://localhost:8080/sys/polymer/polymer.html:5421:6)
    at HTMLTemplateElement.attached (http://localhost:8080/sys/polymer/polymer.html:5402:6)
```

tinymce

**Comment by Mihaiii** [comment]
My bad, it was grunt problem and I didn't noticed it. Please check again.

**Comment by Mackiovello** [comment]
Writing normally works, the buttons give exceptions:
exception

```
Newtonsoft.Json.JsonReaderException: Unterminated string. Expected delimiter: ". Path '[2].value', line 1, position 130877.
   at Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(Char quote)
   at Newtonsoft.Json.JsonTextReader.ParseString(Char quote, ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Starcounter.XSON.JsonPatch.Apply(Json root, JsonTextReader reader, Boolean strictPatchRejection, Object sourceJson, Int32& patchCount) in C:\TeamCity\BuildAgent\work\sc-5591\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 427
   at Starcounter.XSON.JsonPatch.Apply(Json root, String patch, Boolean strictPatchRejection, Int32& patchCount) in C:\TeamCity\BuildAgent\work\sc-5591\Level1\src\Starcounter.XSON\Sessions\JSON-Patch\JsonPatch.cs:line 367
   at Starcounter.Internal.PuppetRestHandler.HandleWebSocketJson(String bs, WebSocket ws) in C:\TeamCity\BuildAgent\work\sc-5591\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\PuppetRestHandler.cs:line 62
   at Starcounter.Internal.AllWsGroups.RunHandler(UInt16 managedHandlerId, UInt32 groupId, WebSocket ws) in C:\TeamCity\BuildAgent\work\sc-5591\Level1\src\Starcounter.Internal\Http\WsManager.cs:line 289
   at Starcounter.GatewayHandlers.HandleWebSocket(UInt16 managedHandlerId, Byte* rawChunk, BMX_TASK_INFO* taskInfo, Boolean* isHandled) in C:\TeamCity\BuildAgent\work\sc-5591\Level1\src\Starcounter\Apps\GatewayHandlers.cs:line 793
LineNumber=1
LinePosition=130877
Path=[2].value
HResult=-2146233088
```

Probably related to https://github.com/Starcounter/level1/issues/4097 (private repo)

**Comment by Mihaiii** [comment]
Well, that's fun: I can't reproduce it.

**Comment by Mackiovello** [comment]
Starcounter version 2.3.1.6633
Content @ https://github.com/StarcounterApps/Content/commit/2e4801567ab4fa1f4cc5fb6d51f2e8d101e92a27
SignIn @ 5.2.0 in the warehouse
Chrome: 58.0.3029.110

It would be good if this could be reproduced by someone else. I know I've had this issue before with certain patches.

**Comment by Mihaiii** [comment]
I think I'll go with tinymce after all so it would be great if someone could try to reproduce.

**Comment by Mihaiii** [comment]
Closing as no longer relevant. Will make another PR after I merge PR #51 .

**Comment by habib535** [comment]
I tried running the above test with `tinymce` branch and it worked for me without any errors!

**Pull request closed without merging**
